# .github/workflows/chromatic.yml

# Workflow name
name: "Chromatic"

on: push

jobs:
    chromatic-deployment:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v1
              with:
                  node-version: "16.x"
            - uses: actions/checkout@v1
            - name: Install dependencies
              run: yarn
            - name: Build
              run: yarn build
            - name: Publish to Chromatic
              uses: chromaui/action@v1
              with:
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
